/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.redscarf.distributedsystems.deadlock;

import com.github.redscarf.distributedsystems.deadlock.models.Conflict;
import com.github.redscarf.distributedsystems.deadlock.factories.BowerProcessorThreadFactory;

public class App {
    public static void main(String[] args) {
        Conflict bowerA = new Conflict("Bower-1207");
        Conflict bowerB = new Conflict("Bower-1911");
        
        Thread firstThread = BowerProcessorThreadFactory.create(bowerA, bowerB);
        Thread secondThread = BowerProcessorThreadFactory.create(bowerB, bowerA);
        
        firstThread.start();
        secondThread.start();
    }
}
